#https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
jobs:
  include:
    - script: "Running unit tests (1)"
    - script: "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true