sudo: required
language: node_js
node_js:
  - stable
addons:
  chrome: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - src

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - cd spec
  - npm i
  - npm i coveralls
  - cd ..
before_script:
  - cd spec
  - npm run lint
  - npm run build
  - cd ..
script:
  - cd spec
  - npm run travis:e2e
  - npm run travis:test

# coveralls.io
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cd ..
after_success:
  - cd spec

  # - https://circleci.com/

  - cd ..

  # - sync with bitbucket/gitlab

  - cp .travis.yml ./dist
  - cp -r .circleci ./dist

deploy:
  provider: pages
  skip_cleanup: true
  
  # https://github.com/settings/tokens
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: gh-pages
  email: torvalds@linux-foundation.org
  name: Linus Torvalds
  on:
    branch: "master"

















# if pr to dev
# - lint build and test
jobs:
  include:
    -
      if: type = pull_request AND $TRAVIS_BRANCH = develop
        - stage: lint
          script:
          - cd src
          - pwd
          - echo v1 typePRandtravisbranchDEVELOP
          - echo before_install > ~/$TRAVIS_BUILD_NUMBER/before_install

# if pr to dev
# - lint build and test
jobs:
  include:
    -
      if: type = pull_request AND branch = develop
        - stage: lint
          script:
          - cd src
          - pwd
          - echo v2 typePRandbranchDEVELOP
          - echo before_install > ~/$TRAVIS_BUILD_NUMBER/before_install

# if pr to dev
# - lint build and test
jobs:
  include:
    -
      if: type = pull_request AND head_branch = develop
        - stage: lint
          script:
          - cd src
          - pwd
          - echo v3 typePRandhead_branchDEVELOP
          - echo before_install > ~/$TRAVIS_BUILD_NUMBER/before_install

# if push to dev
# - lint build and test and sync
jobs:
  include:
    -
      if: type = push AND head_branch = develop
        - stage: lint
          before_install:
          - cd src
          - pwd
          - echo before_install
          - echo before_install > ~/$TRAVIS_BUILD_NUMBER/before_install
          install:
          - pwd
          - echo install
          - echo install > ~/$TRAVIS_BUILD_NUMBER/install
          before_script:
          - pwd
          - echo before_script
          - echo before_script > ~/$TRAVIS_BUILD_NUMBER/before_script
          script:
          - pwd
          - echo script
          - echo script > ~/$TRAVIS_BUILD_NUMBER/script
          - ls -lah
          - ls ~/$TRAVIS_BUILD_NUMBER -lah
          after_success:
          - pwd
          - echo after_success
          - echo after_success > ~/$TRAVIS_BUILD_NUMBER/after_success
        - stage: build
          script:
          - pwd
          - echo script
          - echo script > ~/$TRAVIS_BUILD_NUMBER/script
          - ls -lah
          - ls ~/$TRAVIS_BUILD_NUMBER -lah
        - stage: test
          script:
          - pwd
          - echo script
          - echo script > ~/$TRAVIS_BUILD_NUMBER/script
          - ls -lah
          - ls ~/$TRAVIS_BUILD_NUMBER -lah
        - stage: deploy
          script:
          - pwd
          - echo test--script
          - echo test--script > ~/$TRAVIS_BUILD_NUMBER/test--script
          - ls -lah
          - ls ~/$TRAVIS_BUILD_NUMBER -lah

# if push to master
# - code_coverage and gh-pages and gh-release
jobs:
  include:
    -
      if: type = push AND branch = master
        - stage: lint
          script:
          - cd src
          - pwd
          - echo pushed to master
          - echo before_install > ~/$TRAVIS_BUILD_NUMBER/before_install